id: P008058
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25431
  title: ཡི་དམ་ཆོས་སྐྱོང་ཁག་ཅིག་གི་བྱུང་བ་བརྗོད་པ་ཆོས་ཀུན་གསལ་བའི་ཉིན་བྱེད།
  author: ''
  volumes:
    171738122b664fa49be4a1001b3f9690:
      image_group_id: I1KG25433
      title: Volume 1 of yi dam chos skyong khag cig gi byung ba brjod pa chos kun
        gsal ba'i nyin byed/
      volume_number: 1
      total_pages: 722
      base_file: v001.txt
ebook_metadata:
  title: ཡི་དམ་ཆོས་སྐྱོང་ཁག་ཅིག་གི་བྱུང་བ་བརྗོད་པ་ཆོས་ཀུན་གསལ་བའི་ཉིན་བྱེད།
  author: ''
  sku: P008058
  cover: cover.jpg
  layers:
  - pagination
