id: I4D8448C0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T08:33:06+00:00'
last_modified: '2022-06-08T18:07:54.482527+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25431
  title: ཡི་དམ་ཆོས་སྐྱོང་ཁག་ཅིག་གི་བྱུང་བ་བརྗོད་པ་ཆོས་ཀུན་གསལ་བའི་ཉིན་བྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7595':
      image_group_id: I1KG25433
      title: Volume 1 of yi dam chos skyong khag cig gi byung ba brjod pa chos kun
        gsal ba'i nyin byed/
      total_pages: 722
      order: 1
      base_file: 7595.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
